import { MAX_SESSION_EVENT_TEXT_LENGTH, type LocalSessionRecord } from '../contracts.js';
import { formatSafeRecordType, type SessionIngestionDiagnosticSink } from '../ingestion.js';
import type { CodexRecordDisposition } from './codex-records.js';

const MAX_DEPTH = 64, MAX_KEY_LENGTH = 128;
const safeToolName = /^[A-Za-z0-9_.:/-]{1,128}$/;
const envelopes = ['session_meta', 'event_msg', 'response_item', 'turn_context', 'compacted', 'inter_agent_communication_metadata', 'world_state'];
const responseTypes = ['message', 'reasoning', 'function_call', 'function_call_output', 'custom_tool_call', 'custom_tool_call_output'];
type State = 'whitespace'|'object-key'|'colon'|'value'|'string'|'string-escape'|'unicode-escape'|'number'|'literal'|'container-close';
type Num = 'sign'|'zero'|'integer'|'fraction-start'|'fraction'|'exponent-start'|'exponent-sign'|'exponent';
type ObjPhase = 'key-or-end'|'colon'|'value'|'comma-or-end';
interface Obj { kind: 'object'; path: readonly string[]; phase: ObjPhase; key?: string; afterComma?: boolean; contentType?: string; contentText?: string; }
interface Arr { kind: 'array'; path: readonly string[]; phase: 'value-or-end'|'comma-or-end'; index: number; afterComma?: boolean; }
type Frame = Obj|Arr;

export interface CodexStreamingProjector { write(chunk: Buffer): Promise<void>; finish(): Promise<CodexRecordDisposition>; }
export function createCodexStreamingProjector(input: { readonly sourceOrdinal: number; readonly diagnosticSink?: SessionIngestionDiagnosticSink }): CodexStreamingProjector { return new Projector(input); }

class Projector implements CodexStreamingProjector {
  private readonly decoder = new TextDecoder('utf-8', { fatal: true });
  private readonly stack: Frame[] = []; private readonly values = new Map<string, string>();
  private readonly sourceOrdinal: number; private readonly diagnosticSink?: SessionIngestionDiagnosticSink;
  private state: State = 'whitespace'; private number: Num = 'integer'; private literal = ''; private unicode = '';
  private stringPath: readonly string[] = []; private stringKey = false; private retained = ''; private limit = 0; private overflow = false; private strict = false;
  private rootStarted = false; private rootComplete = false; private payloadObject = false; private structuredOutput = false; private readonly truncatedFields = new Set<string>(); private messageParts: string[] = []; private finished = false; private failed = false;
  public constructor(input: { readonly sourceOrdinal: number; readonly diagnosticSink?: SessionIngestionDiagnosticSink }) { if (!Number.isSafeInteger(input.sourceOrdinal) || input.sourceOrdinal < 0) throw invalid(); this.sourceOrdinal = input.sourceOrdinal; this.diagnosticSink = input.diagnosticSink; }
  public async write(chunk: Buffer): Promise<void> { if (this.finished || this.failed) throw invalid(); try { this.consume(this.decoder.decode(chunk, { stream: true })); } catch { this.failed = true; throw invalid(); } }
  public async finish(): Promise<CodexRecordDisposition> { if (this.finished || this.failed) throw invalid(); this.finished = true; try { this.consume(this.decoder.decode()); if (this.state === 'number' || this.state === 'literal') this.endBare(); if (!this.structural() || !this.rootComplete || this.stack.length) throw invalid(); const result = this.disposition(); if (result.state === 'unsupported') await this.diagnosticSink?.(result.diagnostic); return result; } catch { this.failed = true; throw invalid(); } }
  private consume(text: string): void { for (const ch of text) { let replay = true; while (replay) { replay = false;
    if (this.state === 'string') { if (ch === '"') this.endString(); else if (ch === '\\') this.state = 'string-escape'; else { if (ch < ' ') throw invalid(); this.append(ch); } continue; }
    if (this.state === 'string-escape') { if (ch === 'u') { this.unicode = ''; this.state = 'unicode-escape'; continue; } const map: Record<string,string> = { '"':'"', '\\':'\\', '/':'/', b:'\b', f:'\f', n:'\n', r:'\r', t:'\t' }; if (!(ch in map)) throw invalid(); this.append(map[ch]!); this.state = 'string'; continue; }
    if (this.state === 'unicode-escape') { if (!/[0-9a-f]/i.test(ch)) throw invalid(); this.unicode += ch; if (this.unicode.length === 4) { this.append(String.fromCharCode(Number.parseInt(this.unicode, 16))); this.state = 'string'; } continue; }
    if (this.state === 'number' || this.state === 'literal') { if (this.consumeBare(ch)) continue; this.endBare(); replay = true; continue; }
    if (ws(ch)) continue; if (ch === '"') { this.startString(); continue; } if (ch === '{' || ch === '[') { this.startContainer(ch === '{' ? 'object' : 'array'); continue; } if (ch === '}' || ch === ']') { this.state = 'container-close'; this.close(ch); continue; } if (ch === ':') { this.colon(); continue; } if (ch === ',') { this.comma(); continue; } if (ch === '-' || /[0-9]/.test(ch)) { this.claim(); this.number = ch === '-' ? 'sign' : ch === '0' ? 'zero' : 'integer'; this.state = 'number'; continue; } if (ch === 't' || ch === 'f' || ch === 'n') { this.claim(); this.literal = ch; this.state = 'literal'; continue; } throw invalid();
  } } }
  private startString(): void { const f = this.stack.at(-1); this.stringKey = f?.kind === 'object' && f.phase === 'key-or-end'; if (this.stringKey && f) f.afterComma = false; this.stringPath = this.stringKey ? [] : this.claim(); this.retained = ''; this.overflow = false; this.limit = this.stringKey ? MAX_KEY_LENGTH : this.captureLimit(this.stringPath); this.strict = this.stringKey || (this.limit === MAX_KEY_LENGTH && !this.isTypePath(this.stringPath)); this.state = 'string'; }
  private append(value: string): void { if (!this.limit) return; if (this.retained.length + value.length <= this.limit) this.retained += value; else this.overflow = true; }
  private endString(): void { if (this.stringKey) { if (this.overflow) throw invalid(); const f = this.stack.at(-1); if (f?.kind !== 'object' || f.phase !== 'key-or-end') throw invalid(); f.key = this.retained; f.phase = 'colon'; this.setStructural(); return; } if (this.limit) { if (this.overflow && this.strict) throw invalid(); if (this.overflow) this.truncatedFields.add(this.stringPath.join('/')); this.accept(this.stringPath, this.isTypePath(this.stringPath) && (this.overflow || !safeType(this.retained)) ? '\u0000' : this.retained); } this.complete(); this.setStructural(); }
  private consumeBare(ch: string): boolean { if (this.state === 'literal') { if (!/[A-Za-z]/.test(ch)) return false; if (this.literal.length >= 5) throw invalid(); this.literal += ch; return true; } const delim = ws(ch) || ch === ',' || ch === '}' || ch === ']'; const digit = /[0-9]/.test(ch); if (this.number === 'sign') { if (ch === '0') { this.number='zero'; return true; } if (/[1-9]/.test(ch)) { this.number='integer'; return true; } throw invalid(); } if (this.number === 'zero') { if (ch === '.') { this.number='fraction-start'; return true; } if (ch === 'e'||ch==='E') { this.number='exponent-start'; return true; } if (delim) return false; throw invalid(); } if (this.number === 'integer') { if (digit) return true; if (ch === '.') { this.number='fraction-start'; return true; } if (ch === 'e'||ch==='E') { this.number='exponent-start'; return true; } if (delim) return false; throw invalid(); } if (this.number === 'fraction-start') { if (!digit) throw invalid(); this.number='fraction'; return true; } if (this.number === 'fraction') { if (digit) return true; if(ch==='e'||ch==='E'){this.number='exponent-start';return true;} if(delim)return false;throw invalid(); } if(this.number==='exponent-start'){if(ch==='+'||ch==='-'){this.number='exponent-sign';return true;}if(digit){this.number='exponent';return true;}throw invalid();} if(this.number==='exponent-sign'){if(!digit)throw invalid();this.number='exponent';return true;} if(digit)return true;if(delim)return false;throw invalid(); }
  private endBare(): void { if (this.state === 'number' && !['zero','integer','fraction','exponent'].includes(this.number)) throw invalid(); if (this.state === 'literal' && !['true','false','null'].includes(this.literal)) throw invalid(); this.literal=''; this.complete(); this.setStructural(); }
  private startContainer(kind: 'object'|'array'): void { const path=this.claim(); if(this.stack.length>=MAX_DEPTH)throw invalid(); if(path.join('/')==='payload'&&kind==='object')this.payloadObject=true; if(path.join('/')==='payload/output')this.structuredOutput=true; this.stack.push(kind==='object'?{kind,path,phase:'key-or-end'}:{kind,path,phase:'value-or-end',index:0});this.setStructural(); }
  private close(ch: string): void { const f=this.stack.at(-1);if(!f||(ch==='}'&&f.kind!=='object')||(ch===']'&&f.kind!=='array'))throw invalid();if(f.afterComma||((f.kind==='object'&&!['key-or-end','comma-or-end'].includes(f.phase))||(f.kind==='array'&&!['value-or-end','comma-or-end'].includes(f.phase))))throw invalid();this.stack.pop();if(f.kind==='object'&&f.path.length===3&&f.path[0]==='payload'&&f.path[1]==='content'&&['input_text','output_text','text'].includes(f.contentType??'')&&f.contentText?.trim())this.addPart(f.contentText,f.path);this.complete();this.setStructural(); }
  private colon():void{const f=this.stack.at(-1);if(f?.kind!=='object'||f.phase!=='colon')throw invalid();f.phase='value';this.setStructural();} private comma():void{const f=this.stack.at(-1);if(f?.kind==='object'&&f.phase==='comma-or-end'){f.phase='key-or-end';f.key=undefined;f.afterComma=true;this.setStructural();return;}if(f?.kind==='array'&&f.phase==='comma-or-end'){f.phase='value-or-end';f.afterComma=true;this.setStructural();return;}throw invalid();}
  private claim():readonly string[]{if(!this.stack.length){if(this.rootStarted||this.rootComplete)throw invalid();this.rootStarted=true;return [];}const f=this.stack.at(-1)!;const path=f.kind==='object'?(f.phase==='value'&&f.key!==undefined?[...f.path,f.key]:undefined):(f.phase==='value-or-end'?[...f.path,String(f.index)]:undefined);if(!path)throw invalid();f.afterComma=false;this.prepare(path);return path;}
  private prepare(path:readonly string[]):void{const p=path.join('/');this.truncatedFields.delete(p);if(path.length===4&&path[0]==='payload'&&path[1]==='content'&&(path[3]==='type'||path[3]==='text')){const frame=this.stack.at(-1);if(frame?.kind==='object'){if(path[3]==='type')frame.contentType=undefined;else frame.contentText=undefined;}}if(['timestamp','type','payload/type','payload/name'].includes(p))this.values.delete(p);if(p==='payload'){for(const key of this.values.keys())if(key.startsWith('payload/'))this.values.delete(key);this.truncatedFields.clear();this.payloadObject=false;this.structuredOutput=false;this.messageParts=[];return;}if(['payload/message','payload/arguments','payload/input','payload/output','payload/content','payload/name'].includes(p)){this.values.delete(p);for(const key of this.truncatedFields)if(key===p||key.startsWith(`${p}/`))this.truncatedFields.delete(key);if(p==='payload/output')this.structuredOutput=false;if(p==='payload/content')this.messageParts=[];}}
  private complete():void{if(!this.stack.length){this.rootComplete=true;return;}const f=this.stack.at(-1)!;if(f.kind==='object'){if(f.phase!=='value')throw invalid();f.phase='comma-or-end';return;}if(f.phase!=='value-or-end')throw invalid();f.phase='comma-or-end';f.index+=1;}
  private captureLimit(path:readonly string[]):number{const p=path.join('/');if(['timestamp','type','payload/type','payload/name'].includes(p))return MAX_KEY_LENGTH;const t=this.values.get('payload/type');if(p==='payload/message')return t==='user_message'||t==='agent_message'?MAX_SESSION_EVENT_TEXT_LENGTH:0;if(p==='payload/arguments')return t==='function_call'?MAX_SESSION_EVENT_TEXT_LENGTH:0;if(p==='payload/input')return t==='custom_tool_call'?MAX_SESSION_EVENT_TEXT_LENGTH:0;if(p==='payload/output')return t==='function_call_output'||t==='custom_tool_call_output'?MAX_SESSION_EVENT_TEXT_LENGTH:0;if(p==='payload/content')return t==='message'?MAX_SESSION_EVENT_TEXT_LENGTH:0;if(path.length===4&&path[0]==='payload'&&path[1]==='content'&&t==='message'){if(path[3]==='type')return MAX_KEY_LENGTH;const frame=this.stack.at(-1);return path[3]==='text'&&frame?.kind==='object'&&['input_text','output_text','text'].includes(frame.contentType??'')?MAX_SESSION_EVENT_TEXT_LENGTH:0;}return 0;}
  private accept(path:readonly string[],value:string):void{if(path.length===4&&path[0]==='payload'&&path[1]==='content'){const f=this.stack.at(-1);if(f?.kind==='object'&&f.path.join('/')===path.slice(0,3).join('/')){if(path[3]==='type')f.contentType=value;if(path[3]==='text')f.contentText=value;}return;}this.values.set(path.join('/'),value);}
  private addPart(value:string,path:readonly string[]):void{const used=this.messageParts.reduce((n,x)=>n+x.length,Math.max(0,this.messageParts.length-1)),room=MAX_SESSION_EVENT_TEXT_LENGTH-used-(this.messageParts.length?1:0);if(room<value.length)this.truncatedFields.add(`${path.join('/')}/text`);if(room>0)this.messageParts.push(value.slice(0,room));}
  private setStructural():void{const f=this.stack.at(-1);this.state=!f?'whitespace':f.kind==='object'?(f.phase==='key-or-end'?'object-key':f.phase==='colon'?'colon':f.phase==='value'?'value':'whitespace'):(f.phase==='value-or-end'?'value':'whitespace');}private structural():boolean{return ['whitespace','object-key','colon','value','container-close'].includes(this.state);}
  private disposition():CodexRecordDisposition{const timestamp=this.values.get('timestamp'),type=this.values.get('type');if(timestamp===undefined||type===undefined||!this.payloadObject)throw invalid();if(type==='token_usage_record')return{state:'technical-skip'};if(!envelopes.includes(type))return{state:'unsupported',diagnostic:{code:'UNSUPPORTED_CODEX_RECORD',level:'envelope',recordType:formatSafeRecordType(type),sourceOrdinal:this.sourceOrdinal}};if(['session_meta','turn_context','compacted','inter_agent_communication_metadata','world_state'].includes(type))return this.normalized({kind:'metadata',occurredAt:timestamp});const t=this.values.get('payload/type');if(type==='event_msg')return this.normalized({kind:'message',occurredAt:timestamp,...((t==='user_message'||t==='agent_message')?text(this.values.get('payload/message')):{})});if(t===undefined)throw invalid();if(!responseTypes.includes(t))return{state:'unsupported',diagnostic:{code:'UNSUPPORTED_CODEX_RECORD',level:'response-item',recordType:formatSafeRecordType(t),sourceOrdinal:this.sourceOrdinal}};if(t==='function_call'||t==='custom_tool_call'){const name=this.values.get('payload/name');if(!name||!safeToolName.test(name))throw invalid();return this.normalized({kind:'tool',occurredAt:timestamp,tool:name,...text(this.values.get(t==='function_call'?'payload/arguments':'payload/input'))});}if(t==='function_call_output'||t==='custom_tool_call_output')return this.normalized({kind:'tool',occurredAt:timestamp,...(this.structuredOutput?{}:text(this.values.get('payload/output')))},this.structuredOutput?1:0);return this.normalized({kind:'message',occurredAt:timestamp,...text(t==='message'?(this.values.get('payload/content')??this.messageParts.join('\n')):undefined)});}
  private normalized(record:LocalSessionRecord,omittedStructuredOutputs=0):CodexRecordDisposition{return{state:'normalized',record,truncatedTextFields:this.finalTruncations(),omittedStructuredOutputs};} private isTypePath(path:readonly string[]):boolean{const p=path.join('/');return p==='type'||p==='payload/type';} private finalTruncations():number{const type=this.values.get('type'),subtype=this.values.get('payload/type');let prefix='';if(type==='event_msg'&&(subtype==='user_message'||subtype==='agent_message'))prefix='payload/message';if(type==='response_item'){if(subtype==='function_call')prefix='payload/arguments';else if(subtype==='custom_tool_call')prefix='payload/input';else if(subtype==='function_call_output'||subtype==='custom_tool_call_output')prefix='payload/output';else if(subtype==='message')prefix='payload/content';}return [...this.truncatedFields].filter((key)=>key===prefix||key.startsWith(`${prefix}/`)).length;}
}
function ws(ch:string):boolean{return ch===' '||ch==='\t'||ch==='\n'||ch==='\r';}function safeType(value:string):boolean{return /^[A-Za-z0-9_.:/-]{1,128}$/.test(value);}function text(value:string|undefined):{readonly text?:string}{return value?.trim()?{text:value}:{};}function invalid():Error{return new Error('Codex streaming record is invalid.');}
